import type { Metadata } from 'next';
import localFont from 'next/font/local';
import React from 'react';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                 {/* <nav className="flex items-center justify-center gap-10 text-blue-600">
                  <Link href="/about">About</Link>
                  <Link href="/settings">Settings</Link>
               </nav> */}
                {children}
            </body>
        </html>
    );
}
